language: python

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - USE_DIST="."

python: "3.8"

jobs:
  fast_finish: true
  include:
    - name: Install from repository
      env: USE_DIST="."

    - name: Install from wheel
      env: USE_DIST="dist/*.whl"

    - name: Install from sdist
      env: USE_DIST="dist/*.tar.gz"

install:
  - python -m pip install --upgrade pip wheel
  - python setup.py sdist
  - python setup.py bdist_wheel

script:
  - pip install --progress-bar=off $USE_DIST

